// <auto-generated />
namespace SiteSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Topic_Text_Column_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Topic_Text_Column_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201612050933033_Topic_Text_Column_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
