// <auto-generated />
namespace SiteSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Forum_Requires_Topics : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Forum_Requires_Topics));
        
        string IMigrationMetadata.Id
        {
            get { return "201612041132585_Forum_Requires_Topics"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
