// <auto-generated />
namespace SiteSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Topic_Requires_Forum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Topic_Requires_Forum));
        
        string IMigrationMetadata.Id
        {
            get { return "201612041135096_Topic_Requires_Forum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
